service: raffle

frameworkVersion: ">=1.1.0 <2.0.0"

package:
  exclude:
    - node_modules/**
    
provider:
  name: aws
  runtime: python2.7
  profile: serverless-admin
  region: sa-east-1

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  list:
    handler: handler.listDownloadFiles
    events:
      - http:
          path: files
          method: get
          cors: true
  # cron:
  #   handler: handler.run
  #   events:
  #     # Invoke Lambda function every minute
  #     - schedule: rate(1 minute)

plugins:
  - serverless-python-requirements
